//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AmazonRest.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class AmazonUsersEntities : DbContext
    {
        public AmazonUsersEntities()
            : base("name=AmazonUsersEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<User> Users { get; set; }
    
        public virtual ObjectResult<Nullable<int>> AuthenticateUser(string emailOrPhone, string password)
        {
            var emailOrPhoneParameter = emailOrPhone != null ?
                new ObjectParameter("EmailOrPhone", emailOrPhone) :
                new ObjectParameter("EmailOrPhone", typeof(string));
    
            var passwordParameter = password != null ?
                new ObjectParameter("Password", password) :
                new ObjectParameter("Password", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("AuthenticateUser", emailOrPhoneParameter, passwordParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> Authenticate_User(string emailOrPhone, string password)
        {
            var emailOrPhoneParameter = emailOrPhone != null ?
                new ObjectParameter("EmailOrPhone", emailOrPhone) :
                new ObjectParameter("EmailOrPhone", typeof(string));
    
            var passwordParameter = password != null ?
                new ObjectParameter("Password", password) :
                new ObjectParameter("Password", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("Authenticate_User", emailOrPhoneParameter, passwordParameter);
        }
    }
}
